# Generated by Django 4.2.10 on 2026-09-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeXDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='未命名文档', max_length=200, verbose_name='标题')),
                ('source', models.TextField(verbose_name='TeX 源码')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='PDF 文件')),
                ('status', models.CharField(choices=[('success', '编译成功'), ('failed', '编译失败')], max_length=10, verbose_name='状态')),
                ('log', models.TextField(blank=True, default='', verbose_name='编译日志')),
                ('duration', models.FloatField(default=0, verbose_name='编译耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'TeX 文档',
                'verbose_name_plural': 'TeX 文档',
                'ordering': ['-created_at'],
            },
        ),
    ]
