# Generated by Django 4.2.10 on 2026-09-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名项目', max_length=200, verbose_name='标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'TeX 项目',
                'verbose_name_plural': 'TeX 项目',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='texdocument',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True, unique=True, verbose_name='分享令牌'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/', verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='converter.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目资源',
                'verbose_name_plural': '项目资源',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='texdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='converter.project', verbose_name='来源项目'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('is_main', models.BooleanField(default=False, verbose_name='主文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='converter.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件',
                'ordering': ['-is_main', 'filename'],
                'unique_together': {('project', 'filename')},
            },
        ),
    ]
