# Generated by Django 4.2.10 on 2026-10-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_project_texdocument_share_token_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用 AI')),
                ('api_base', models.CharField(blank=True, default='', max_length=255, verbose_name='API 地址')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API Key')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='模型名称')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 配置',
                'verbose_name_plural': 'AI 配置',
            },
        ),
    ]
